const projectData = {
    "Cybersecurity": [
        "Threat Intelligence Dashboard with Public Threat Feeds Integration",
        "Dynamic Security Policy Enforcer for Web Applications",
        "Phishing Awareness Simulation and Reporting Tool",
        "Wi-Fi Security Analyzer with Vulnerability Detection",
        "Network Anomaly Detection Using Machine Learning (Python-Based)",
        "Custom Network Scanner with Port Scanning and Service Detection",
        "Malware Detection Tool Using Signature-Based Analysis",
        "AI-Based Intrusion Detection System (IDS) for Network Traffic",
        "Cybersecurity Risk Assessment Tool for Mobile Payment Apps",
        "Secure Password Strength Analyzer with Breach Detection API Integration",
        "Firewall Rule Management and Traffic Filtering Simulator",
        "Ransomware Detection System Using File Activity Monitoring",
        "Secure File Transfer System with End-to-End Encryption",
        "Web Application Vulnerability Scanner (OWASP-Based Checks)",
        "Log Analysis and Threat Detection System Using SIEM Concepts"
    ],
    "iOS Development": [
        "Context-Aware Digital Wellbeing Assistant Using On-Device Behavior Analysis",
        "AI-Based Scam Call and Message Risk Detection System",
        "Privacy Risk Analyzer for Mobile Apps with Real-Time Alerts",
        "Offline-First Emergency Communication App Using Peer-to-Peer Connectivity",
        "Cognitive Load-Aware Study Assistant with Adaptive Break Scheduling",
        "Dynamic Focus Mode Controller Based on User Activity Patterns",
        "AI-Powered Misinformation Detection for News and Social Media",
        "Personal Data Usage Visualizer with Predictive Alerts",
        "Voice Stress and Emotional State Monitoring App for Mental Wellbeing",
        "Smart Notification Prioritization System Using Behavioral Learning",
        "Decentralized Identity Wallet with Secure Credential Storage",
        "Energy Consumption Awareness App Using Device Usage Analytics"
    ],
    "Machine Learning": [
        "Energy Consumption Prediction Using Machine Learning",
        "Agricultural Yield Prediction Using Predictive Modeling",
        "Facial Recognition System Using Supervised Learning",
        "Taxi Route Optimization Using Reinforcement Learning",
        "Breast Cancer Detection Using Machine Learning Models",
        "Speech Emotion Recognition Using Machine Learning",
        "Spam Email Detection Using Classification Algorithms",
        "Smart Traffic Management System Using Machine Learning",
        "Heart Disease Prediction Using Logistic Regression",
        "Handwritten Digit Recognition Using Scikit-Learn",
        "Object Counting System Using Python and OpenCV",
        "Face Counting System Using Python and OpenCV",
        "Loan Eligibility Prediction Using Machine Learning Models",
        "Bitcoin Price Prediction Using Machine Learning",
        "Demand Forecasting Model Using Machine Learning"
    ],
    "Artificial Intelligence": [
        "AI-Based Traffic Management System",
        "AI-Driven Waste Management System",
        "AI-Based Game Development (Tic-Tac-Toe / Snake)",
        "AI Chatbot for College Enquiry System",
        "AI-Powered Resume Screening System",
        "AI-Based Logistics Chatbot System",
        "Intelligent Chatbot / Voice Assistant",
        "AI-Powered Career Recommendation System",
        "Smart Virtual Personal Assistant Using AI",
        "Emotion Detection Using Facial Expression Analysis",
        "AI-Based Shopping Assistant (Shopping Buddy)",
        "AI Productivity Assistant (Task Automation Agent)",
        "Voice-to-Action Automation System Using AI",
        "Multi-Agent AI Collaboration System",
        "AI-Based Body Language Recognition System"
    ],
    "Full-Stack Web Development": [
        "Smart Ambulance Booking and Emergency Response System",
        "Trip Expense Management and Sharing Web App",
        "Full-Stack E-Commerce Bookstore with Payment Integration",
        "Automated Invoice Generation and Billing System",
        "Online Fire Reporting and Incident Management System",
        "Synthetic Data Generation Platform for AI Training",
        "Habit Tracking and Productivity Analytics Web App",
        "Blogging Platform with CMS",
        "Personal Portfolio Website with Admin Dashboard",
        "Multi-User Blog Website with Authentication & Roles",
        "Real-Time Chat Application with WebSockets",
        "Online Food Ordering and Delivery System",
        "Event Management and Ticket Booking System",
        "Job Portal with Resume Upload and Employer Dashboard",
        "Online Code Collaboration and Execution Platform"
    ],
    "Software Development": [
        "Real-Time Scalable Chat Application (WebSocket + Queue)",
        "AI-Powered Movie Recommendation System",
        "Intelligent Route Planning System with Traffic Prediction",
        "Full-Stack Social Media Platform with Real-Time Feed",
        "AI-Based Language Translation System",
        "Peer-to-Peer File Sharing System with Secure Transfer",
        "Smart Weather Forecasting and Alert System",
        "AI-Based Study Planner with Personalized Scheduling",
        "Distributed File Storage System with Replication",
        "Real-Time Collaborative Document Editor (Google Docs Clone)",
        "Online Code Execution Platform with Secure Sandbox",
        "Multi-Tenant SaaS Application with Role-Based Access",
        "Microservices-Based E-Commerce Backend System",
        "AI-Based Resume Parsing and Job Matching System",
        "Online Quiz and Assessment Platform"
    ],
    "Android Development": [
        "Android-Based Bookstore App with Authentication",
        "Smart Alarm System with Intelligent Scheduling",
        "Graphical Password Authentication System",
        "Secure Android Voting System",
        "Bus Pass Management System",
        "Hotel Reservation App",
        "Bluetooth-Based Chat Application",
        "Book Sharing Platform",
        "Android Messaging App with Real-Time Communication",
        "Currency Detection App for Visually Impaired",
        "Women Safety App with Emergency Alerts",
        "College Recommendation App",
        "Peer-to-Peer Study Material Sharing App",
        "Campus Navigation & Event Discovery App",
        "Subscription Management App with Payment Reminders"
    ],
    "Data Visualization": [
        "Zomato Data Analysis and Insights",
        "IPL Data Analysis with Team Strategy Insights",
        "Airbnb Pricing & Occupancy Analysis",
        "COVID-19 Interactive Dashboard",
        "Housing Price Prediction & Analysis",
        "Market Basket Analysis",
        "Customer Churn Analysis",
        "Car Price Prediction Analysis",
        "Indian Election Data Visualization",
        "HR Analytics Dashboard",
        "Product Recommendation Analysis",
        "Credit Card Risk Analysis",
        "Uber Trip Demand Analysis",
        "Mobile Sales Trend Analysis",
        "Nobel Prize Data Visualization Dashboard",
        "Movie Box Office Analysis Dashboard",
        "Flight Price Trend Visualization"
    ],
    "Data Science": [
        "Zomato Data Analysis Using Python",
        "IPL Data Analysis",
        "Indian Election Data Analysis",
        "COVID-19 Data Analysis & Visualization",
        "Air Quality Analysis",
        "Climate Change Data Analysis",
        "Unemployment Rate Analysis",
        "Stock Price Time Series Analysis",
        "Cryptocurrency Time Series Analysis",
        "Gold Price Forecasting",
        "Food Price Forecasting",
        "Sales Forecasting",
        "Demand Forecasting",
        "SMS Spam Detection Using TensorFlow"
    ]
};

export default projectData;
